CREATE TABLE IF NOT EXISTS USER
	(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USERNAME TEXT NOT NULL UNIQUE);

CREATE INDEX IF NOT EXISTS USERNAME_INDEX ON USER (USERNAME);

CREATE TABLE IF NOT EXISTS USERLOTTERY
	(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USER_ID INTEGER NOT NULL,
	LOTTERY_NAME TEXT NOT NULL,
	LOTTERY_ID INTEGER NOT NULL);

CREATE INDEX IF NOT EXISTS LOTTERY_INDEX ON USERLOTTERY (LOTTERY_NAME, LOTTERY_ID);
